# Render deployment configuration
services:
  - type: web
    name: peerstorm-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: |
      python manage.py migrate
      gunicorn --bind 0.0.0.0:$PORT --workers 3 peerstorm.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: peerstorm.settings.production
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: FRONTEND_URL
        value: https://newrevolution.netlify.app
    
  - type: worker
    name: peerstorm-celery
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A peerstorm worker --loglevel=info
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: peerstorm.settings.production
    
  - type: cron
    name: peerstorm-celery-beat
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A peerstorm beat --loglevel=info
    schedule: "0 * * * *"  # Run every hour
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: peerstorm.settings.production

databases:
  - name: peerstorm-db
    databaseName: peerstorm_db
    user: peerstorm_user

  - name: peerstorm-redis
    type: redis